name: e2e

on: [pull_request]

env:
  GO_VERSION: 1.18

jobs:

  
  e2e:
    runs-on: ubuntu-latest

    name: Prebuilt kernel module
 
    steps:

      - uses: actions/checkout@v3
      - name: Create the test's infra 
        run: source ./ci/github/create_infra && build_cluster && build_controller && build_driver_container

      - name: Run e2e-prebuilt-kernel-module 
        run: ./ci/prow/e2e-prebuilt-kernel-module


  e2e-two-nodes:
    name: Prebuilt kernel module - two nodes

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create the test's infra
        run: source ./ci/github/create_infra --nodes 2 && build_cluster && build_controller && build_driver_container

      - name: Run e2e-prebuilt-kernel-module-two-nodes
        run: ./ci/prow/e2e-prebuilt-kernel-module-two-nodes

  in-cluster-build:
    name: In-cluster build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Create the test's infra
        run: source ./ci/github/create_infra --addons registry,registry-aliases && build_internal_registry_driver_container

      - name: Run e2e-incluster-build
        run: ./ci/prow/e2e-incluster-build


  e2e-crd-variable:
    name: Container image CRD variable

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - name: Create the test's infra
        run: source ./ci/github/create_infra && build_cluster && build_controller && build_driver_container

      - name: Run e2e-crd-variable
        run: ./ci/prow/e2e-crd-variable







